<?php

/**
 * -----------------------------------------------------------------------------
 * Generated 2023-05-26T18:36:54+05:30
 *
 * DO NOT EDIT THIS FILE DIRECTLY
 *
 * @item      server_timezone
 * @group     app
 * @namespace null
 * -----------------------------------------------------------------------------
 */
return [
    'server_timezone' => 'Asia/Kolkata',
];
