<?php

/**
 * -----------------------------------------------------------------------------
 * Generated 2023-07-03T22:06:48+05:30
 *
 * DO NOT EDIT THIS FILE DIRECTLY
 *
 * @item      cache.last_cleared
 * @group     concrete
 * @namespace null
 * -----------------------------------------------------------------------------
 */
return [
    'version_installed' => '9.1.3',
    'version_db_installed' => '20220908074900',
    'misc' => [
        'login_redirect' => 'HOMEPAGE',
        'access_entity_updated' => 1685106411,
    ],
    'cache' => [
        'last_cleared' => 1688402208,
        'blocks' => false,
        'assets' => false,
        'theme_css' => true,
        'overrides' => true,
        'pages' => '0',
        'full_page_lifetime' => 'default',
        'clear' => [
            'thumbnails' => true,
        ],
    ],
    'theme' => [
        'compress_preprocessor_output' => true,
        'generate_less_sourcemap' => false,
    ],
];
