<?php

/**
 * -----------------------------------------------------------------------------
 * Generated 2023-06-14T01:41:33+05:30
 *
 * DO NOT EDIT THIS FILE DIRECTLY
 *
 * @item      sites.default.multilingual.always_track_user_locale
 * @group     site
 * @namespace null
 * -----------------------------------------------------------------------------
 */
return [
    'sites' => [
        'default' => [
            'name' => 'Araksha',
            'multilingual' => [
                'redirect_home_to_default_locale' => false,
                'use_browser_detected_locale' => true,
                'default_source_locale' => 'en_US',
                'always_track_user_locale' => false,
            ],
        ],
    ],
];
